# Generated by Django 3.0.8 on 2020-12-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=300)),
                ('Choice_1', models.CharField(max_length=100)),
                ('Choice_2', models.CharField(max_length=100)),
                ('Choice_3', models.CharField(max_length=100)),
                ('Choice_4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Details',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=100)),
                ('no_of_questions', models.IntegerField()),
                ('Mark_per_question', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('update_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizid', to='Quiz.Quiz_Details')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz_details',
            name='quiz_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Topic'),
        ),
        migrations.AddField(
            model_name='quiz_details',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Teacher'),
        ),
        migrations.CreateModel(
            name='check_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=100)),
                ('check_result', models.BooleanField(default=False)),
                ('correct_answer', models.ForeignKey(db_column='correct_answer', on_delete=django.db.models.deletion.CASCADE, related_name='correctanswers', to='Quiz.add_question')),
                ('qu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questid', to='Quiz.Quiz_Details')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.add_question')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Student')),
            ],
        ),
        migrations.AddField(
            model_name='add_question',
            name='quiz_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz_Details'),
        ),
    ]
