# Generated by Django 2.1.15 on 2021-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210105_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_details',
            name='questions_entered',
            field=models.IntegerField(default=0),
        ),
    ]
